[project]
name = "data-store360"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "anourhamuze33", email = "anourhamuze@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "seaborn>=0.13.2",
]

[project.scripts]
data-store360 = "data_store360:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
